package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewAnimationNodeBlend3FromPointer(ptr gdnative.Pointer) AnimationNodeBlend3 {
func newAnimationNodeBlend3FromPointer(ptr gdnative.Pointer) AnimationNodeBlend3 {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := AnimationNodeBlend3{}
	obj.SetBaseObject(owner)

	return obj
}

/*
A resource to add to an [AnimationNodeBlendTree]. Blends two animations together linearly out of three based on a value in the [code][-1.0, 1.0][/code] range. This node has three inputs: - The base animation - A -blend animation to blend with when the blend amount is in the [code][-1.0, 0.0][/code] range. - A +blend animation to blend with when the blend amount is in the [code][0.0, 1.0][/code] range
*/
type AnimationNodeBlend3 struct {
	AnimationNode
	owner gdnative.Object
}

func (o *AnimationNodeBlend3) BaseClass() string {
	return "AnimationNodeBlend3"
}

/*
        Undocumented
	Args: [], Returns: bool
*/
func (o *AnimationNodeBlend3) IsUsingSync() gdnative.Bool {
	//log.Println("Calling AnimationNodeBlend3.IsUsingSync()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 0, 0)

	// Get the method bind
	methodBind := gdnative.NewMethodBind("AnimationNodeBlend3", "is_using_sync")

	// Call the parent method.
	// bool
	retPtr := gdnative.NewEmptyBool()
	gdnative.MethodBindPtrCall(methodBind, o.GetBaseObject(), ptrArguments, retPtr)

	// If we have a return type, convert it from a pointer into its actual object.
	ret := gdnative.NewBoolFromPointer(retPtr)
	return ret
}

/*
        Undocumented
	Args: [{ false enable bool}], Returns: void
*/
func (o *AnimationNodeBlend3) SetUseSync(enable gdnative.Bool) {
	//log.Println("Calling AnimationNodeBlend3.SetUseSync()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 1, 1)
	ptrArguments[0] = gdnative.NewPointerFromBool(enable)

	// Get the method bind
	methodBind := gdnative.NewMethodBind("AnimationNodeBlend3", "set_use_sync")

	// Call the parent method.
	// void
	retPtr := gdnative.NewEmptyVoid()
	gdnative.MethodBindPtrCall(methodBind, o.GetBaseObject(), ptrArguments, retPtr)

}

// AnimationNodeBlend3Implementer is an interface that implements the methods
// of the AnimationNodeBlend3 class.
type AnimationNodeBlend3Implementer interface {
	AnimationNodeImplementer
	IsUsingSync() gdnative.Bool
	SetUseSync(enable gdnative.Bool)
}
