package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewAudioStreamMicrophoneFromPointer(ptr gdnative.Pointer) AudioStreamMicrophone {
func newAudioStreamMicrophoneFromPointer(ptr gdnative.Pointer) AudioStreamMicrophone {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := AudioStreamMicrophone{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type AudioStreamMicrophone struct {
	AudioStream
	owner gdnative.Object
}

func (o *AudioStreamMicrophone) BaseClass() string {
	return "AudioStreamMicrophone"
}

// AudioStreamMicrophoneImplementer is an interface that implements the methods
// of the AudioStreamMicrophone class.
type AudioStreamMicrophoneImplementer interface {
	AudioStreamImplementer
}
