package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewCSGCombinerFromPointer(ptr gdnative.Pointer) CSGCombiner {
func newCSGCombinerFromPointer(ptr gdnative.Pointer) CSGCombiner {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := CSGCombiner{}
	obj.SetBaseObject(owner)

	return obj
}

/*
Undocumented
*/
type CSGCombiner struct {
	CSGShape
	owner gdnative.Object
}

func (o *CSGCombiner) BaseClass() string {
	return "CSGCombiner"
}

// CSGCombinerImplementer is an interface that implements the methods
// of the CSGCombiner class.
type CSGCombinerImplementer interface {
	CSGShapeImplementer
}
