package godot

import (
	"github.com/shadowapex/godot-go/gdnative"
)

/*------------------------------------------------------------------------------
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "class.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/

//func NewVisualShaderNodeColorConstantFromPointer(ptr gdnative.Pointer) VisualShaderNodeColorConstant {
func newVisualShaderNodeColorConstantFromPointer(ptr gdnative.Pointer) VisualShaderNodeColorConstant {
	owner := gdnative.NewObjectFromPointer(ptr)
	obj := VisualShaderNodeColorConstant{}
	obj.SetBaseObject(owner)

	return obj
}

/*

 */
type VisualShaderNodeColorConstant struct {
	VisualShaderNode
	owner gdnative.Object
}

func (o *VisualShaderNodeColorConstant) BaseClass() string {
	return "VisualShaderNodeColorConstant"
}

/*
        Undocumented
	Args: [], Returns: Color
*/
func (o *VisualShaderNodeColorConstant) GetConstant() gdnative.Color {
	//log.Println("Calling VisualShaderNodeColorConstant.GetConstant()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 0, 0)

	// Get the method bind
	methodBind := gdnative.NewMethodBind("VisualShaderNodeColorConstant", "get_constant")

	// Call the parent method.
	// Color
	retPtr := gdnative.NewEmptyColor()
	gdnative.MethodBindPtrCall(methodBind, o.GetBaseObject(), ptrArguments, retPtr)

	// If we have a return type, convert it from a pointer into its actual object.
	ret := gdnative.NewColorFromPointer(retPtr)
	return ret
}

/*
        Undocumented
	Args: [{ false value Color}], Returns: void
*/
func (o *VisualShaderNodeColorConstant) SetConstant(value gdnative.Color) {
	//log.Println("Calling VisualShaderNodeColorConstant.SetConstant()")

	// Build out the method's arguments
	ptrArguments := make([]gdnative.Pointer, 1, 1)
	ptrArguments[0] = gdnative.NewPointerFromColor(value)

	// Get the method bind
	methodBind := gdnative.NewMethodBind("VisualShaderNodeColorConstant", "set_constant")

	// Call the parent method.
	// void
	retPtr := gdnative.NewEmptyVoid()
	gdnative.MethodBindPtrCall(methodBind, o.GetBaseObject(), ptrArguments, retPtr)

}

// VisualShaderNodeColorConstantImplementer is an interface that implements the methods
// of the VisualShaderNodeColorConstant class.
type VisualShaderNodeColorConstantImplementer interface {
	VisualShaderNodeImplementer
	GetConstant() gdnative.Color
	SetConstant(value gdnative.Color)
}
